### PR TITLE
fix unspent utxo challenging attempt crashing ExitProcessor

### LINKED ISSUE #1180: "no match of right hand side value: :not_found" when challenging SE
Sentry Issue: [ELIXIR-OMG-24](https://sentry.io/organizations/omisego/issues/1358932689/?referrer=github_integration)

```
exit: ** (exit) exited in: GenServer.call(OMG.Watcher.ExitProcessor, {:create_challenge, {:utxo_position, 1000, 0, 0}}, 5000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: :not_found
            (omg_watcher) lib/omg_watcher/exit_processor.ex:470: OMG.Watcher.ExitProcessor.do_get_spent_blknum/1
            (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
            (omg_watcher) lib/omg_watcher/exit_processor.ex:452: OMG.Watcher.ExitProcessor.do_get_spending_blocks/1
            (omg_watcher) lib/omg_watcher/exit_processor.ex:393: OMG.Watcher.ExitProcessor.fill_request_with_standard_challenge_data/1
            (omg_watcher) lib/omg_watcher/exit_processor.ex:381: OMG.Watcher.ExitProcessor.handle_call/3
            (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
  File "lib/gen_server.ex", line 989, in GenServer.call/3
  File "lib/web/controllers/challenge.ex", line 32, in OMG.WatcherRPC.Web.Controller.Challenge.get_utxo_challenge/2
  File "lib/web/controllers/challenge.ex", line 15, in OMG.WatcherRPC.Web.Controller.Challenge.action/2
  File "lib/web/controllers/challenge.ex", line 15, in OMG.WatcherRPC.Web.Controller.Challenge.phoenix_controller_pipeline/2
  File "lib/web/endpoint.ex", line 15, in OMG.WatcherRPC.Web.Endpoint.instrument/4
...
(3 additional frame(s) were not displayed)

(ErlangError) Erlang error: {{{:badmatch, :not_found}, [{OMG.Watcher.ExitProcessor, :do_get_spent_blknum, 1, [file: 'lib/omg_watcher/exit_processor.ex', line: 470]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1327]}, {OMG.Watcher.ExitProcessor, :do_get_spending_blocks, 1, [file: 'lib/omg_watcher/exit_processor.ex', line: 452]}, {OMG.Watcher.ExitProcessor, :fill_request_with_standard_challenge_data, 1, [file: 'lib/omg_watcher/exit_processor.ex', line: 393]}, {OMG.Watcher.ExitProcessor, :handle_call, 3, [file: 'lib/omg_watcher/exit_processor.ex', line: 381]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}, {GenServer, :call, [OMG.Watcher.ExitProcessor, {:create_challenge, {:utxo_position, 1000, 0, 0}}, 5000]}}
```

### PR DESCRIPTION
**Pull request by pdobacz**
Fixes #1180 

## Overview

The problem lied in incorrect handling of a spending_block `:not_found` - `{:ok, :not_found}` was expected, but this form was since long deprecated in favor of the former.

Also this was uncleanly realized too late, so a peek into `OMG.State` was added to figure out the challengeability of the requested exit.

## Changes

- fix the bug, sprinkle some tests
- change the **`test`** env `ChildChainRPC` port number to `9657` to avoid the super-annoying clash with the default
- groom the specs in `OMG.DB`

## Testing

`mix test`

### CODE REVIEW

File: apps/omg_watcher/test/omg_watcher/exit_processor/standard_exit_test.exs [hunk 1]
```diff
@@ -56,14 +56,32 @@ defmodule OMG.Watcher.ExitProcessor.StandardExitTest do
   end
 
   describe "Core.determine_standard_challenge_queries" do
+    test "doesn't ask for anything and stops if deposit utxo not spent at all",
+         %{alice: alice, processor_empty: processor} do
+      processor = processor |> start_se_from_deposit(@utxo_pos_deposit, alice)
```
Comment (pdobacz) [inline apps/omg_watcher/test/omg_watcher/exit_processor/standard_exit_test.exs]: yes, I know, single pipes. But before this is raised, please observe how consistent and aesthetically uniform this allows this file to be. Style makes us to avoid **"needless pipe" (not "single")**, I consider this a non-needless pipe (from the perspective of the entire file's context).

If this is, regardless of the argument given, deemed unacceptable, then <sigh>... I can ofc adjust

File: apps/omg_db/lib/omg_db/rocks_db.ex [hunk 2]
```diff
@@ -92,12 +92,10 @@ if Code.ensure_loaded?(:rocksdb) do
       GenServer.call(server_name, :competitors_info, @one_minute)
     end
 
-    @spec exit_info({pos_integer, non_neg_integer, non_neg_integer}, atom) :: {:ok, map} | {:error, atom}
```
Comment (pnowosie) [inline apps/omg_db/lib/omg_db/rocks_db.ex]: removing specs always looks suspicious - why?

File: apps/omg_watcher/lib/omg_watcher/exit_processor/standard_exit.ex [hunk 3]
```diff
@@ -91,14 +91,22 @@ defmodule OMG.Watcher.ExitProcessor.StandardExit do
...
+        exiting_utxo_exists
       ) do
-    with {:ok, _exit_info} <- get_exit(exits, exiting_pos) do
-      spending_blocks_to_get = if get_ife_based_on_utxo(exiting_pos, state), do: [], else: [exiting_pos]
+    with {:ok, _exit_info} <- get_exit(exits, exiting_pos),
+         # once figured out the exit exists, check if it is spent in an IFE?
+         ife_based_on_utxo = get_ife_based_on_utxo(exiting_pos, state),
+         # To be challengable, the exit utxo must be spent in either an IFE or missing from the `OMG.State`.
+         # In the latter case we'll go on looking for the spending tx in the `OMG.DB`
+         true <- !is_nil(ife_based_on_utxo) || !exiting_utxo_exists || {:error, :utxo_not_spent} do
```
Comment (pnowosie) [inline apps/omg_watcher/lib/omg_watcher/exit_processor/standard_exit.ex]: Haha, this is clever :+1:

File: apps/omg_watcher/test/omg_watcher/exit_processor/standard_exit_test.exs (hunk 1 above)
Comment (pnowosie) [reply apps/omg_watcher/test/omg_watcher/exit_processor/standard_exit_test.exs]: How dare you @pdobacz you betrayed __The Convention__ we all agreed on :exclamation: 
[crying profusely :cry: not really want the fix]

File: apps/omg_db/lib/omg_db/rocks_db.ex (hunk 2 above)
Comment (pdobacz) [reply apps/omg_db/lib/omg_db/rocks_db.ex]: the rest doesn't have it and this one was incorrect, so I just went with the majority. The specs are in the behavior module.

I can apply them here as well, if there's consensus

File: apps/omg_watcher/lib/omg_watcher/exit_processor/standard_exit.ex (hunk 3 above)
Comment (pdobacz) [reply apps/omg_watcher/lib/omg_watcher/exit_processor/standard_exit.ex]: hm, so maybe I should un-clever this :thinking:. `Boring is better`

File: apps/omg_watcher/test/omg_watcher/exit_processor/standard_exit_test.exs (hunk 1 above)
Comment (pdobacz) [reply apps/omg_watcher/test/omg_watcher/exit_processor/standard_exit_test.exs]: I'm serious, I want to follow the style, I'm just making an argument here: I think this is warranted and within the style limits.

Comment (unnawut) [reply apps/omg_watcher/test/omg_watcher/exit_processor/standard_exit_test.exs]: I havn't made up my mind on this yet. Some places single pipes make sense, other places make it harder to read.

But in this case, I like how it can be read as a natural sentence so I'm letting this through.
