### PR TITLE
Fix sla margin config

### LINKED ISSUE #1079: watcher configuration for EXIT_PROCESSOR_SLA_MARGIN
```
watcher_1          | 2019-10-29 10:51:51.146 [info] module=OMG.Watcher.ExitProcessor function=init/1 ⋅Initializing with: {:ok, %OMG.Watcher.ExitProcessor.Core{competitors: %{}, exit_ids: %{}, exits: %{}, in_flight_exits: %{}, sla_margin: {:system, "EXIT_PROCESSOR_SLA_MARGIN", 5520, {String, :to_integer}}}}⋅
```

### PR DESCRIPTION
**Pull request by pdobacz**
fixes #1079 

## Overview

A cherrypick from `v0.2` led to an invalid entry in the configuration for `:exit_processor_sla_margin`. This fixes that, introducing a new config provider, see commit `
fix: introduce a config provider for exit_processor_sla_margin setting`

## Changes

On top of the actual fix, I ran into a couple of things to tidy around the release_tasks (separate commit `style: cleanup release_tasks`):
- change log level from warn to info
- add more teardown procedures in tests (in cases where it was missing)
- use catch_exit in all tests

## Testing

`mix test`

### CODE REVIEW

File: apps/omg_child_chain_rpc/test/omg_child_chain_rpc/release_tasks/set_tracer_test.exs [hunk 1]
```diff
@@ -48,12 +57,7 @@ defmodule OMG.ChildChainRPC.ReleaseTasks.SetTracerTest do
...
   test "if exit is thrown when faulty configuration is used" do
     :ok = System.put_env("DD_DISABLED", "TRUEeee")
-
-    try do
-      :ok = SetTracer.init([])
-    catch
-      :exit, _ ->
-        :ok = System.delete_env("DD_DISABLED")
-    end
+    catch_exit(SetTracer.init([]))
```
Comment (InoMurko) [inline apps/omg_child_chain_rpc/test/omg_child_chain_rpc/release_tasks/set_tracer_test.exs]: WOW

**Comment by pdobacz** [comment]
> Did you actually delete `exit_processor_sla_margin: {:system, "EXIT_PROCESSOR_SLA_MARGIN", 23 * 60 * 4, {String, :to_integer}},`?

haha, I just noticed that I didn't. I pushing the fix now. Good catch :)
