### PR TITLE
fix: CaseClauseError in Watcher.ExitProcessor when there are multiple exits

### LINKED ISSUE #1235: CaseClauseError when watcher detects a new exit
@jbunce spotted exceptions after deploying fcb7088 to an environment

```elixir
2019-12-26 06:24:52.110 [info] module=OMG.Watcher.ExitProcessor function=init/1 ⋅Initializing with: {:ok, %OMG.Watcher.ExitProcessor.Core{competitors: %{}, exit_ids: %{2032413964260704897224450687663723715858437494 => {:utxo_position, 1000, 0, 0}}, exits: %{{:utxo_position, 1000, 0, 0} => %OMG.Watcher.ExitProcessor.ExitInfo{amount: 5000000000000000, currency: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, eth_height: 9140291, exit_id: 2032413964260704897224450687663723715858437494, exiting_txbytes: <<248, 178, 1, 225, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59, 154, 202, 0, 248, 107, ...>>, is_active: true, owner: <<226, 86, 72, 222, 91, 193, 132, 211, 132, 72, 238, 195, 155, 69, 8, 148, 11, 109, 130, 189>>}}, in_flight_exits: %{}, sla_margin: 5520}}⋅

2019-12-26 06:24:52.110 [info] module=OMG.EthereumEventListener function=handle_continue/2 ⋅Starting OMG.EthereumEventListener for exit_processor.⋅

2019-12-26 06:24:52.349 [info] module=OMG.EthereumEventListener function=handle_continue/2 ⋅Started OMG.EthereumEventListener for exit_processor, synced_height: 9159296⋅

2019-12-26 06:25:01.161 [info] module=OMG.Watcher.ExitProcessor function=handle_call/3 ⋅Recognized exits: [%{call_data: %{output_tx: <<248, 90, 1, 192, 245, 244, 1, 242, 148, 69, 34, 251, 68, 194, 171, 53, 158, 118, 236, 199, 92, 34, 201, 64, 150, 144, 241, 34, 65, 148, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, output_tx_inclusion_proof: <<243, 154, 134, 159, 98, 231, 92, 245, 240, 191, 145, 70, 136, 166, 178, 137, 202, 242, 4, 148, 53, 216, 230, 140, 92, 94, 109, 5, 228, 73, 19, 243, 78, 213, 192, 45, 109, 72, 200, 147, 36, 134, 201, 157, 58, 217, ...>>, utxo_pos: 2002000000000}, eth_height: 9159513, event_signature: "ExitStarted(address,uint160)", exit_id: 832615825608379901973646435154383854844284432, log_index: 28, owner: <<69, 34, 251, 68, 194, 171, 53, 158, 118, 236, 199, 92, 34, 201, 64, 150, 144, 241, 34, 65>>, root_chain_txhash: <<95, 207, 90, 66, 96, 113, 210, 151, 115, 233, 124, 149, 84, 82, 146, 37, 110, 94, 76, 78, 60, 220, 154, 128, 197, 133, 222, 243, 142, 31, 56, 215>>}, %{call_data: %{output_tx: <<248, 123, 1, 225, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 210, 204, 97, 208, 0, 245, 244, 1, 242, 148, 69, 34, 251, 68, ...>>, output_tx_inclusion_proof: <<243, 154, 134, 159, 98, 231, 92, 245, 240, 191, 145, 70, 136, 166, 178, 137, 202, 242, 4, 148, 53, 216, 230, 140, 92, 94, 109, 5, 228, 73, 19, 243, 78, 213, 192, 45, 109, 72, 200, 147, 36, 134, 201, 157, 58, ...>>, utxo_pos: 16000000000000}, eth_height: 9159947, event_signature: "ExitStarted(address,uint160)", exit_id: 1875022375984755883891285225420292204154037250, log_index: 117, owner: <<69, 34, 251, 68, 194, 171, 53, 158, 118, 236, 199, 92, 34, 201, 64, 150, 144, 241, 34, 65>>, root_chain_txhash: <<166, 99, 126, 59, 158, 6, 30, 150, 5, 68, 26, 213, 136, 48, 211, 29, 181, 50, 67, 191, 161, 182, 57, 148, 189, 199, 122, 78, 131, 86, 0, 112>>}]⋅

2019-12-26 06:25:01.402 [error] module=gen_server function=error_info/7 ⋅GenServer OMG.Watcher.ExitProcessor terminating

** (CaseClauseError) no case clause matching: 2
(ex_abi) lib/abi/type_decoder.ex:258: ABI.TypeDecoder.decode_type/2
(ex_abi) lib/abi/type_decoder.ex:233: anonymous fn/2 in ABI.TypeDecoder.decode_type/2
(elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
(ex_abi) lib/abi/type_decoder.ex:228: ABI.TypeDecoder.decode_type/2
(ex_abi) lib/abi/type_decoder.ex:233: anonymous fn/2 in ABI.TypeDecoder.decode_type/2
(elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
(ex_abi) lib/abi/type_decoder.ex:228: ABI.TypeDecoder.decode_type/2
(ex_abi) lib/abi/type_decoder.ex:222: ABI.TypeDecoder.decode_type/2

Last message (from :exit_processor): {:new_exits, [%{call_data: %{output_tx: <<248, 90, 1, 192, 245, 244, 1, 242, 148, 69, 34, 251, 68, 194, 171, 53, 158, 118, 236, 199, 92, 34, 201, 64, 150, 144, 241, 34, 65, 148, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, output_tx_inclusion_proof: <<243, 154, 134, 159, 98, 231, 92, 245, 240, 191, 145, 70, 136, 166, 178, 137, 202, 242, 4, 148, 53, 216, 230, 140, 92, 94, 109, 5, 228, 73, 19, 243, 78, 213, 192, 45, 109, 72, 200, 147, 36, 134, 201, 157, ...>>, utxo_pos: 2002000000000}, eth_height: 9159513, event_signature: "ExitStarted(address,uint160)", exit_id: 832615825608379901973646435154383854844284432, log_index: 28, owner: <<69, 34, 251, 68, 194, 171, 53, 158, 118, 236, 199, 92, 34, 201, 64, 150, 144, 241, 34, 65>>, root_chain_txhash: <<95, 207, 90, 66, 96, 113, 210, 151, 115, 233, 124, 149, 84, 82, 146, 37, 110, 94, 76, 78, 60, 220, 154, 128, 197, 133, 222, 243, 142, 31, 56, 215>>}, %{call_data: %{output_tx: <<248, 123, 1, 225, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 210, 204, 97, 208, 0, 245, 244, 1, 242, 148, 69, 34, ...>>, output_tx_inclusion_proof: <<243, 154, 134, 159, 98, 231, 92, 245, 240, 191, 145, 70, 136, 166, 178, 137, 202, 242, 4, 148, 53, 216, 230, 140, 92, 94, 109, 5, 228, 73, 19, 243, 78, 213, 192, 45, 109, 72, 200, 147, 36, 134, 201, ...>>, utxo_pos: 16000000000000}, eth_height: 9159947, event_signature: "ExitStarted(address,uint160)", exit_id: 1875022375984755883891285225420292204154037250, log_index: 117, owner: <<69, 34, 251, 68, 194, 171, 53, 158, 118, 236, 199, 92, 34, 201, 64, 150, 144, 241, 34, 65>>, root_chain_txhash: <<166, 99, 126, 59, 158, 6, 30, 150, 5, 68, 26, 213, 136, 48, 211, 29, 181, 50, 67, 191, 161, 182, 57, 148, 189, 199, 122, 78, 131, 86, 0, 112>>}]}⋅

```

### PR DESCRIPTION
**Pull request by unnawut**
Closes #1235 

## Overview

Fixes `OMG.Watcher.ExitProcessor` crashing repetitively when >=2 exits started in parallel.

## Changes

- Replace the fixed-size array signature with a variable-length array signature when decoding the response from `"standardExits(uint160[])"`, i.e. passing `{:array, struct}` signature instead of `{:array, struct, length}` to `ABI.TypeDecoder.decode/2`.
- Bump up the local geth snapshot to `20191225-MIN_EXIT_PERIOD-20-PLASMA_CONTRACTS_SHA-835d10cbe8d7ef56feb745f71de638f85f572f7d.tar.gz` where we can cross-check the contract addresses from auto-releases. The previous snapshot was from pre-release era.
- Re-record ExVCRs for `OMG.Eth.RootChainTest` because they were way out of date that new tests cannot be added withour re-recording.
- Man, adding the `OMG.Eth.RootChain.get_standard_exits_structs/2` test was hard! Thanks to @achiurizo for the help.

See the full explanation at https://github.com/omisego/elixir-omg/issues/1235#issuecomment-569044217.

## Testing

```
mix test test/omg_eth/root_chain_test.exs:214
```

Or start two standard exits then spin the `watcher` (or `watcher_info`) up. GenServer crash loop from `CaseClauseError` should not appear.

### CODE REVIEW

File: apps/omg_eth/test/omg_eth/root_chain_test.exs [hunk 1]
```diff
@@ -73,44 +70,42 @@ defmodule OMG.Eth.RootChainTest do
...
+  test "get_deposits/3 returns deposit events", %{contracts: contracts} do
     use_cassette "ganache/get_deposits", match_requests_on: [:request_body] do
       # not using OMG.ChildChain.Transaction to not depend on that in omg_eth tests
       # payment tx_type, no inputs, one output, metadata
       tx =
-        [1, [], [[1, contract.authority_address, @eth, 1]], <<0::256>>]
-        |> ExRLP.encode()
+        [owner: contracts.authority_address, currency: @eth, amount: 1]
+        |> ExPlasma.Transactions.Deposit.new()
+        |> ExPlasma.Transaction.encode()
```
Comment (achiurizo) [inline apps/omg_eth/test/omg_eth/root_chain_test.exs]: 🎇

File: apps/omg_eth/lib/omg_eth/root_chain.ex [hunk 2]
```diff
@@ -376,7 +375,7 @@ defmodule OMG.Eth.RootChain do
     )
   end
 
-  defp decode_exit_started(log) do
+  def decode_exit_started(log) do
```
Comment (InoMurko) [inline apps/omg_eth/lib/omg_eth/root_chain.ex]: if you want to test this function you should extract it to a separate module so that it becomes available for unit testing... it seems like it's not used >in code<

File: apps/omg_eth/test/omg_eth/root_chain_test.exs [hunk 3]
```diff
@@ -126,4 +121,56 @@ defmodule OMG.Eth.RootChainTest do
               ]} = deposits
     end
   end
+
+  describe "get_standard_exits_structs/2" do
```
Comment (InoMurko) [inline apps/omg_eth/test/omg_eth/root_chain_test.exs]: this is what you can cover with a end2end test in priv/

File: apps/omg_eth/test/support/root_chain_helper.ex [hunk 4]
```diff
@@ -333,4 +333,18 @@ defmodule Support.RootChainHelper do
 
     deposit_blknum
   end
+
+  def exit_id_from_receipt(%{"logs" => logs}) do
```
Comment (InoMurko) [inline apps/omg_eth/test/support/root_chain_helper.ex]: this could easily live inside the tests where its used

File: apps/omg_eth/test/omg_eth/root_chain_test.exs [hunk 5]
```diff
@@ -29,31 +29,28 @@ defmodule OMG.Eth.RootChainTest do
...
-      # NOTE: achiurizo
-      # this has changed with ALD(see plasma-contrats deploy of plasma_framework)
-      # it's now :plasma_framework_tx_hash instead of :txhash_contract
-      txhash_contract: Encoding.from_hex("0x3d517d431daea71a99310f12468ffdf2bf547ad1d148f42acfc4ee34dd4e84d7"),
-      plasma_framework: Encoding.from_hex("0xd17e1233a03affb9092d5109179b43d6a8828607"),
-      eth_vault: Encoding.from_hex("0x1967d06b1faba91eaadb1be33b277447ea24fa0e"),
-      erc20_vault: Encoding.from_hex("0xaef6182310e3d34b6ea138b60d36a245386f3201"),
-      payment_exit_game: Encoding.from_hex("0x902719f192aa5240632f704aa7a94bab61b86550"),
-      authority_address: Encoding.from_hex("0x22d491bde2303f2f43325b2108d26f1eaba1e32b")
+    contracts = %{
```
Comment (InoMurko) [inline apps/omg_eth/test/omg_eth/root_chain_test.exs]: these could also get read from file. like `deffixture contract(eth_node) do`. wdyt?

File: apps/omg_eth/lib/omg_eth/root_chain.ex [hunk 6]
```diff
@@ -76,8 +76,7 @@ defmodule OMG.Eth.RootChain do
     contract = Config.maybe_fetch_addr!(contract, :payment_exit_game)
 
     static_array_return_types = [
-      {:array, {:tuple, [:bool, {:uint, 256}, {:bytes, 32}, :address, {:uint, 256}, {:uint, 256}]},
-       Enum.count(exit_ids)}
+      {:array, {:tuple, [:bool, {:uint, 256}, {:bytes, 32}, :address, {:uint, 256}, {:uint, 256}]}}
```
Comment (pdobacz) [inline apps/omg_eth/lib/omg_eth/root_chain.ex]: :+1: and I don't know why I figured that, after stripping out the offest part from https://solidity.readthedocs.io/en/v0.5.13/abi-spec.html#use-of-dynamic-types, what remains should be decoded as a static array. It is still a dynamic array and encoded like you mentioned in #1235, the offset prefix is like "an other kind of dynamicness" involved. Not fully grasping this yet but makes sense.

However, since now this is fixed, the naming and comments I originally put there become bit confusing. Lemme suggest:
  - `static_array_return_types` -> `return_types`
  - `proceeds to decode the array as if it were static` -> `proceeds to decode the array without the offset`
  - `static_array_data::binary` -> `raw_array_data::binary`

File: apps/omg_eth/test/omg_eth/root_chain_test.exs (hunk 5 above)
Comment (unnawut) [reply apps/omg_eth/test/omg_eth/root_chain_test.exs]: Sounds good. Looks like `deffixture contract` is being used in only one test file I should be able to remove this fixture completely. Let me do it in a separate PR.

File: apps/omg_eth/lib/omg_eth/root_chain.ex (hunk 2 above)
Comment (unnawut) [reply apps/omg_eth/lib/omg_eth/root_chain.ex]: Updated in 84d6fc67de63477e104fcce55a7d83c316523957

File: apps/omg_eth/test/support/root_chain_helper.ex (hunk 4 above)
Comment (unnawut) [reply apps/omg_eth/test/support/root_chain_helper.ex]: Updated in 84d6fc67de63477e104fcce55a7d83c316523957

File: apps/omg_eth/lib/omg_eth/root_chain.ex (hunk 6 above)
Comment (unnawut) [reply apps/omg_eth/lib/omg_eth/root_chain.ex]: Updated in 2594ee448a66ff6f5873d83901ec424e2ba79bcb

File: apps/omg_eth/test/omg_eth/root_chain_test.exs (hunk 3 above)
Comment (unnawut) [reply apps/omg_eth/test/omg_eth/root_chain_test.exs]: Drafting as https://github.com/omisego/elixir-omg/pull/1243

File: apps/omg_eth/test/omg_eth/root_chain_test.exs [hunk 7]
```diff
@@ -73,44 +70,42 @@ defmodule OMG.Eth.RootChainTest do
     # Skipping these specs for now as this function needs to be updated
     # to use the new ALD function (not hasToken?)
     @tag :skip
-    test "returns false if no token exists", %{contract: contract} do
+    test "returns false if no token exists", %{contracts: contracts} do
```
Comment (InoMurko) [inline apps/omg_eth/test/omg_eth/root_chain_test.exs]: these are all skipped and they're testing the rootchainhelper (wtf?) I think we can safely delete this. has_token doesn't even exist!
