### PR TITLE
Fix "piggyback_available" popping back after challenge

### LINKED ISSUE #1318: Split invalidly processed exit from unchallenged exit events
Coming from #1275, which in the end opted to take a different approach to solve.

> separate the conflated unchallenged_exit from invalidly_processed_exit and have things called by their name. The conflating of those events is too much of a stop-gap solution to continue with.
> 
> Then things get easier - when an exit processes invalidly (which was Gerhard's case) we'll get a dedicated event invalidly_processed_exit.
> 
> And as a consequence, we'll have more freedom in setting exit_processor_sla_margin, which drives unchallenged_exit. This is because we'll then set it to something larger than min_exit_period, which matters in cases where min_exit_period is really small.

This has its own merit, since conflating of the notions of an unchallenged exit and of an exit that processed invalidly under a single report (`unchallenged_exit`) and logic is messy and hard to understand by someone who's looking.

### LINKED ISSUE #1371: Challenged, invalid piggybacks may pop back to `piggyback_available` state
This happens in the cases where the IFE tx never got included.

The reason is [`is_piggybacked?`](https://github.com/omisego/elixir-omg/blob/master/apps/omg_watcher/lib/omg_watcher/exit_processor/in_flight_exit_info.ex#L346) is used when figuring `piggyback_available` out. If `true`, that report won't be shown.

However, challenging a piggyback flips `:is_piggybacked` to `false` [here](https://github.com/omisego/elixir-omg/blob/master/apps/omg_watcher/lib/omg_watcher/exit_processor/in_flight_exit_info.ex#L296).

Nice fix: #1318 and introduce a better data model (enums _in lieu_ of a bunch of boolean values).

Quick fix: introduce `is_challenged` field in the `exit_map`

### PR DESCRIPTION
**Pull request by pdobacz**
Closes #1371 

## Overview

It is the "Quick fix" mentioned in #1371. The larger fix #1318 would do proper justice to the handling of piggyback state (description of that in #1318 still pending), which should not be modeled with a bunch of booleans. There should also be a revamp done to the overall "lifecycle" of the piggyback, to include invalidly processing ones.

## Changes

 - adds a simple test picking up the case in question, in `piggyback_test.exs`
 - refactors some other tests and inner working of `InFlightExitInfo`. We're interrested in the notions of 1/ "activity" of a piggyback, where it means it may finalize and we perhaps want to check if it is valid and 2/ "being piggybacked", where it means just this.
 - it finally adds an explicit notion of `is_challenged` to the IFE's piggyback model. Whenever a piggyback challenge happens it now turns that `true` instead of turning `is_piggybacked` to `false`, which led to the error

## Testing

the usual tests apply. Also I'll use this in the revamped IFE tests prepared as part of #1344, where we will challange invalid piggybacks and require that they do not show up as "`piggyback_available`" anymore

### CODE REVIEW

**Comment by pdobacz** [comment]
@paulperegud @pnowosie

It seems I introduced a regression along the way. ef7ee5afc5c4659d14aa6724625f72d60874cb34 exposes this in a test and 766e69c fixes.

Would you be so kind to take another glance at this?

**Comment by pdobacz** [comment]
_sigh_ and one more regression picked up and fixed in 73fdb85 & f417502

File: apps/omg_watcher/test/support/exit_processor/test_helper.ex [hunk 1]
```diff
@@ -25,7 +25,7 @@ defmodule OMG.Watcher.ExitProcessor.TestHelper do
 
   require Utxo
 
-  @exit_id 1
+  @exit_id 9876
```
Comment (pnowosie) [inline apps/omg_watcher/test/support/exit_processor/test_helper.ex]: It's unlikely that somebody needs to change the value, and it'll be discovered quickly but maybe to be nice can you add a comment saying the value is used by other tests?
Thanks!
