### PR TITLE
fix: fix reporting unavailable piggyback as available

### LINKED ISSUE #495: Piggybacked outputs are reported as available when calling status.get endpoint in Watcher
After in-flight exit output is piggybacked, status.get endpoint still reports it as available for piggybacking.

To reproduce that follow docs/demo04 and after starting an in-flight exit:
1. piggyback onto one of the outputs
2. wait until watcher recognizes the piggyback
3. call status.get endpoint and look for event that reports piggybacked output as still available

### PR DESCRIPTION
**Pull request by pgebal**
Closes  #495

### CODE REVIEW

File: apps/omg_watcher/lib/exit_processor/core.ex [hunk 1]
```diff
@@ -911,44 +911,54 @@ defmodule OMG.Watcher.ExitProcessor.Core do
...
   defp get_ifes_to_piggyback(
          %ExitProcessor.Request{blocks_result: blocks},
          %__MODULE__{in_flight_exits: ifes}
        ) do
     known_txs = get_known_txs(blocks)
 
     ifes
-    |> Map.values()
-    |> Stream.map(fn %InFlightExitInfo{tx: signed_tx} -> signed_tx end)
+    |> Stream.filter(fn {_, %InFlightExitInfo{is_active: is_active}} -> is_active end)
```
Comment (pdobacz) [inline apps/omg_watcher/lib/exit_processor/core.ex]: I think the flows can be cleaner here:
1/ keep `Map.values`, as you don't need the keys ever
2/ keep passing around `ife`, instead of the tuple `ife, signed_tx`
3/ pattern-match the `signed_tx` field out of `ife` only when needed, instead of pattern-matching it out of the tuple.

The tuple passed through the pipeline is redundant (ife contains signed tx)

File: apps/omg_watcher/lib/exit_processor/in_flight_exit_info.ex [hunk 2]
```diff
@@ -215,6 +215,14 @@ defmodule OMG.Watcher.ExitProcessor.InFlightExitInfo do
     end
   end
 
+  def is_input_piggybacked?(%__MODULE__{} = ife, index) when is_integer(index) and index < @max_inputs do
```
Comment (pdobacz) [inline apps/omg_watcher/lib/exit_processor/in_flight_exit_info.ex]: if we're positive about doing this refactor then maybe `is_piggybacked` can be private, and the verbose function be used in consumers of this module

File: apps/omg_watcher/test/exit_processor/core_test.exs [hunk 3]
```diff
@@ -773,6 +773,67 @@ defmodule OMG.Watcher.ExitProcessor.CoreTest do
...
+      finalization = %{in_flight_exit_id: @non_zero_exit_id, output_index: 0}
+
+      {:ok, processor, _} = Core.finalize_in_flight_exits(processor, [finalization])
+
+      assert {:ok, []} =
+               %ExitProcessor.Request{blknum_now: 1000, eth_height_now: 5}
+               |> invalid_exits_filtered(processor, only: [Event.PiggybackAvailable])
+    end
+
+    test "in-flight exit without piggybacked outputs does not emit piggyback available event after it's finalized" do
```
Comment (pdobacz) [inline apps/omg_watcher/test/exit_processor/core_test.exs]: but is there a reason this cannot work and be tested in the logic level here? It looks like a simple condition that we can handle in our Core and test it here just fine. Looks like it'd be worth for completeness

File: apps/omg_watcher/test/integration/in_flight_exit_test.exs [hunk 4]
```diff
@@ -295,8 +295,7 @@ defmodule OMG.Watcher.Integration.InFlightExitTest do
              "byzantine_events" => [
```
Comment (pdobacz) [inline apps/omg_watcher/test/integration/in_flight_exit_test.exs]: how about the comment we talked about in the upper assertion? (why only one pb available?)

File: docs/api_specs/status_events_specs.md [hunk 5]
```diff
@@ -132,8 +132,7 @@ txbytes | Hex encoded string | The in-flight transaction that the event relates
 }
 ```
 
-An in-flight exit has been started and can be piggybacked. If all inputs are owned by the same address, then `available_inputs` will not be present.
-<aside class="warning"> Not Implemented Yet.</aside>
+An in-flight exit has been started and can be piggybacked. If all inputs are owned by the same address, then `available_inputs` will not be present. This event is reported only for in-flight exits from transactions that have not been included in a block.
```
Comment (pdobacz) [inline docs/api_specs/status_events_specs.md]: ah when we're at it - document the behavior your fixing in this PR:
1/ piggybacked inputs/outputs don't show up as available
2/ finalized ones don't either

File: apps/omg_watcher/test/exit_processor/core_test.exs (hunk 3 above)
Comment (pgebal) [reply apps/omg_watcher/test/exit_processor/core_test.exs]: As discussed, I removed that test.

File: apps/omg_watcher/lib/exit_processor/in_flight_exit_info.ex (hunk 2 above)
Comment (pgebal) [reply apps/omg_watcher/lib/exit_processor/in_flight_exit_info.ex]: We need is_piggybacked to be public. There is a use case in core where we don't know if we are asking for tx inputs or outputs. See `with` in `finalize_in_flight_exits`.

Comment (pdobacz) [reply apps/omg_watcher/lib/exit_processor/in_flight_exit_info.ex]: ok, nvm then, we can reassess that when we go about refactoring all this
