### PR TITLE
fix: finalize in-flight exits in Watcher

### LINKED ISSUE #630: Watcher allows for spending in-flight exited utxos
In Watcher utxos exited via in-flight exit are available for spend after the exit is finalized. It means that operator can produce transactions that stem from exited utxos and Watcher accepts them as valid.

### PR DESCRIPTION
**Pull request by pgebal**
Partly solves #630. Exited utxo can no longer be spent, but IFEs are not reflected in convenience API. That will be solved in a separate PR.

Closes #630.

### CODE REVIEW

File: apps/omg_eth/lib/eth.ex [hunk 1]
```diff
@@ -175,7 +175,7 @@ defmodule OMG.Eth do
     end
   end
 
-  defp event_topic_for_signature(signature) do
+  def event_topic_for_signature(signature) do
```
Comment (InoMurko) [inline apps/omg_eth/lib/eth.ex]: why is this public?

Comment (pgebal) [reply apps/omg_eth/lib/eth.ex]: It shouldn't be, this code is not for review yet.

Comment (pgebal) [reply apps/omg_eth/lib/eth.ex]: @InoMurko Fixes are uploaded, feel free to have a look.

File: apps/omg/lib/omg/state/core.ex [hunk 2]
```diff
@@ -405,7 +405,6 @@ defmodule OMG.State.Core do
   def exit_utxos([%{tx_hash: _} | _] = piggybacks, %Core{utxos: utxos} = state) do
     piggybacks
     |> Enum.map(fn %{tx_hash: tx_hash, output_index: oindex} ->
-      # oindex in contract is 0-7 where 4-7 are outputs
```
Comment (pdobacz) [inline apps/omg/lib/omg/state/core.ex]: I think this comment might have been helpful. This subtraction is otherwise rather cryptic

File: apps/omg_watcher/lib/omg_watcher/exit_processor.ex [hunk 3]
```diff
@@ -273,8 +273,12 @@ defmodule OMG.Watcher.ExitProcessor do
 
   def handle_call({:finalize_in_flight_exits, finalizations}, _from, state) do
     _ = if not Enum.empty?(finalizations), do: Logger.info("Recognized ife finalizations: #{inspect(finalizations)}")
-    {:ok, state, db_updates} = Core.finalize_in_flight_exits(state, finalizations)
-    {:reply, {:ok, db_updates}, state}
+
+    {:ok, state, db_updates, input_exits, output_exits} = Core.finalize_in_flight_exits(state, finalizations)
+    {:ok, input_exits_state_updates, _} = State.exit_utxos(input_exits)
+    {:ok, output_exits_state_updates, _} = State.exit_utxos(output_exits)
```
Comment (pdobacz) [inline apps/omg_watcher/lib/omg_watcher/exit_processor.ex]: there still is a large step missing here, which is taking validities into account, to cover the case where an IFE finalizes invalidly. But that's another large leap to take, so perhaps another issue/PR. And it would require to introduce the concept of a late invalid IFE, so that SEs and IFEs finally behave on par.

Maybe as a bare minimum, grab the invalid utxos (second list in the `_`-out tuple in the return), concatenate both flavors (inputs outputs) and if that list is non-empty (some IFE in-out-puts finalized invalidly) print a `Logger.warn` with some message and positions (make sure to inspect).

Leaving a TODO or a NOTE and reference to an issue is also desired

File: apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex [hunk 4]
```diff
@@ -366,7 +366,9 @@ defmodule OMG.Watcher.ExitProcessor.Core do
   end
 
   @spec finalize_in_flight_exits(t(), [map()]) ::
-          {:ok, t(), list()} | {:unknown_piggybacks, list()} | {:unknown_in_flight_exit, MapSet.t(non_neg_integer())}
+          {:ok, t(), list(), list(), list()}
```
Comment (pdobacz) [inline apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex]: let's put a `doc` here explaining what the args and returns are. This just got way more complicated.

**Among other** explanations, make sure to include what the kinds of lists are the two new lists - that they "fit" to whatever `State.Core` likes to receive in `exit_utxos` while handling IFEs.

Comment (pdobacz) [reply apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex]: Next, add tests under `state_interaction_test.exs`, that check that whatever you're feeding `State.Core` makes sense.

You can even add a test, where some IFE finalizes invalidly and check if you're getting the Logger warning for completeness (`ExUnit.CaptureLog`). Later we'd swap this test for test of more proper handling.

This combined should give you decent test coverage of the IFE finalization

File: apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs [hunk 5]
```diff
@@ -1326,21 +1326,47 @@ defmodule OMG.Watcher.ExitProcessor.CoreTest do
   end
 
   describe "in-flight exit finalization" do
-    test "deactivate in-flight exit after all piggybacked outputs are finalized",
-         %{processor_empty: processor, transactions: [tx | _]} do
+    test "deactivate in-flight exit after all piggybacked transaction inputs are finalized",
```
Comment (pdobacz) [inline apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs]: leave this test as it was and add a new test (or tests) that test your new behaviors

Comment (pdobacz) [reply apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs]: another comment related to this. Judging by the test description, you're triggering exiting in `State` only when all piggybacks have finalized? I think this is too late - you should exit in `State` when a particular piggybacked in/output finalizes immediately.

If this is just about the test description, and you're exiting immediately, then the implementation is fine; splitting the test and/or amending the description will do!

File: apps/omg_watcher/lib/omg_watcher/exit_processor.ex (hunk 3 above)
Comment (pgebal) [reply apps/omg_watcher/lib/omg_watcher/exit_processor.ex]: done

File: apps/omg_watcher/lib/omg_watcher/exit_processor.ex [hunk 6]
```diff
@@ -438,4 +436,26 @@ defmodule OMG.Watcher.ExitProcessor do
...
+    {:ok, output_exits_state_updates, {_, output_invalidities}} = State.exit_utxos(output_exits)
+
+    exit_invalidities = input_invalidities ++ output_invalidities
+
+    {state, db_updates} =
+      if Enum.empty?(exit_invalidities) do
+        {state, db_updates}
+      else
+        _ = Logger.warn("Invalid in-flight exit finalization: #{inspect(exit_invalidities)}")
+        Core.activate_in_flight_exit(state, ife_id)
```
Comment (pgebal) [inline apps/omg_watcher/lib/omg_watcher/exit_processor.ex]: I'd like to talk about that. Ping me when you read this.

File: apps/omg/lib/omg/state/core.ex [hunk 7]
```diff
@@ -403,18 +403,29 @@ defmodule OMG.State.Core do
...
-    |> exit_utxos(state)
+    {piggybacks_of_unknown_utxos, piggybacks_of_known_utxos} =
+      piggybacks
+      |> Enum.map(fn %{tx_hash: tx_hash, output_index: oindex} = piggyback ->
+        # oindex in contract is 0-7 where 4-7 are outputs
+        oindex = oindex - 4
+
+        position =
+          utxos
+          |> Map.to_list()
```
Comment (InoMurko) [inline apps/omg/lib/omg/state/core.ex]: code like this, with massive pipes... is this really necessary?

File: apps/omg/lib/omg/state/core.ex [hunk 8]
```diff
@@ -403,18 +403,29 @@ defmodule OMG.State.Core do
...
-      utxos
-      |> Map.to_list()
-      |> Enum.find(&match?({Utxo.position(_, _, ^oindex), %Utxo{creating_txhash: ^tx_hash}}, &1))
-    end)
-    |> Enum.filter(&(&1 != nil))
-    |> Enum.map(fn {position, _} -> position end)
-    |> exit_utxos(state)
+    {piggybacks_of_unknown_utxos, piggybacks_of_known_utxos} =
+      piggybacks
+      |> Enum.map(fn %{tx_hash: tx_hash, output_index: oindex} = piggyback ->
```
Comment (InoMurko) [inline apps/omg/lib/omg/state/core.ex]: maybe these big pipes are not the optimal approach to this? what if you pull the implementation out into a private function and document the function separately + specs?

Comment (pdobacz) [reply apps/omg/lib/omg/state/core.ex]: ah, I concur about pulling the implementation out to a `defp`, but I'd leave all 3 pipes in the diff in :)

Comment (pgebal) [reply apps/omg/lib/omg/state/core.ex]: done

File: apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs [hunk 9]
```diff
@@ -1325,22 +1325,126 @@ defmodule OMG.Watcher.ExitProcessor.CoreTest do
...
+      ife_id2 = 2
+      tx_hash1 = Transaction.raw_txhash(tx1)
+      tx_hash2 = Transaction.raw_txhash(tx2)
+
+      processor =
+        processor
+        |> start_ife_from(tx1, status: {1, ife_id1})
+        |> start_ife_from(tx2, status: {1, ife_id2})
+
+      {processor, _} = Core.new_piggybacks(processor, [%{tx_hash: tx_hash1, output_index: 0}])
```
Comment (pdobacz) [inline apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs]: with the increased amounts of calls to `Core.new_piggybacks`, I think it's time to do a refactoring due:

Follow the same approach as `start_ife_from(tx, status: {1, ife_id})` -> `piggyback_ife_from(tx, output_index)` so that we can append the `|> piggyback_ife_from(...)` to the pipes like above.

Direct calls to `Core.new_piggybacks` would stay on the few occasions where it is more convenient/ilustrative or where we want to do sth with the db updates

File: apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs [hunk 10]
```diff
@@ -1325,22 +1325,126 @@ defmodule OMG.Watcher.ExitProcessor.CoreTest do
...
+
+      {:unknown_piggybacks, ^expected_unknown_piggybacks} =
+        Core.prepare_utxo_exits_for_in_flight_exit_finalizations(processor, [finalization1, finalization2])
+    end
+  end
+
   describe "in-flight exit finalization" do
-    test "deactivate in-flight exit after all piggybacked outputs are finalized",
+    test "exits piggybacked transaction inputs",
+         %{
```
Comment (pdobacz) [inline apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs]: single line the `%{...} do`

File: apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs [hunk 11]
```diff
@@ -1356,8 +1460,8 @@ defmodule OMG.Watcher.ExitProcessor.CoreTest do
         |> Core.new_piggybacks([%{tx_hash: tx_hash, output_index: 1}])
 
       finalization = %{in_flight_exit_id: ife_id, output_index: 1}
-      {:ok, processor, _} = Core.finalize_in_flight_exits(processor, [finalization])
-      {:ok, ^processor, []} = Core.finalize_in_flight_exits(processor, [finalization])
+      {:ok, processor, _} = Core.finalize_in_flight_exits(processor, [finalization], %{})
+      {:ok, ^processor, _} = Core.finalize_in_flight_exits(processor, [finalization], %{})
```
Comment (pdobacz) [inline apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs]: here I think the assertion that no more stuff is written do db was relevant. Pls revert the `[]`

File: apps/omg_watcher/test/omg_watcher/exit_processor/persistence_test.exs [hunk 12]
```diff
@@ -253,7 +253,7 @@ defmodule OMG.Watcher.ExitProcessor.PersistenceTest do
   end
 
   defp persist_finalize_ifes(processor, finalizations, db_pid) do
-    {:ok, processor, db_updates} = Core.finalize_in_flight_exits(processor, finalizations)
+    {:ok, processor, db_updates} = Core.finalize_in_flight_exits(processor, finalizations, [])
```
Comment (pdobacz) [inline apps/omg_watcher/test/omg_watcher/exit_processor/persistence_test.exs]: usually the last arg is a map

File: apps/omg_watcher/lib/omg_watcher/exit_processor.ex [hunk 13]
```diff
@@ -434,4 +442,22 @@ defmodule OMG.Watcher.ExitProcessor do
     {:ok, spend_blknum} = position |> Utxo.Position.to_db_key() |> OMG.DB.spent_blknum()
     spend_blknum
   end
+
+  defp collect_invalidities_and_state_db_updates(
+         {ife_id, {input_exits, output_exits}},
+         {invalidities_by_ife_id, state_db_updates}
+       ) do
+    {:ok, input_exits_state_updates, {_, input_invalidities}} = State.exit_utxos(input_exits)
```
Comment (pdobacz) [inline apps/omg_watcher/lib/omg_watcher/exit_processor.ex]: leave also a comment here
```
# we can't call `State.exit_utxos(input_exits ++ output_exits)` because the types of these enumerable items are distinct
```

File: apps/omg_watcher/test/omg_watcher/exit_processor/core/state_interaction_test.exs [hunk 14]
```diff
@@ -182,6 +182,74 @@ defmodule OMG.Watcher.ExitProcessor.Core.StateInteractionTest do
     assert Utxo.position(1, 0, 0) in spends_to_get
   end
 
+  test "can work with State to exit utxos from in-flight transactions", %{
+    processor_empty: processor,
```
[the remark this answers is not in the document]
Comment (pgebal) [reply apps/omg_watcher/test/omg_watcher/exit_processor/core/state_interaction_test.exs]: Done

File: apps/omg/test/omg/state/core_test.exs [hunk 15]
```diff
@@ -624,6 +624,13 @@ defmodule OMG.State.CoreTest do
     assert {:ok, {[], {[], [^utxo_pos_exit_1]}}, ^state} = Core.exit_utxos([utxo_pos_exit_1], state)
   end
 
+  @tag fixtures: [:state_empty]
```
[the remark this answers is not in the document]
Comment (pgebal) [reply apps/omg/test/omg/state/core_test.exs]: Ad 1. That's tested in the test above this one.
Ad 2. Done.

File: apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs (hunk 10 above)
Comment (pgebal) [reply apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs]: Done

File: apps/omg_watcher/test/omg_watcher/exit_processor/persistence_test.exs (hunk 12 above)
Comment (pgebal) [reply apps/omg_watcher/test/omg_watcher/exit_processor/persistence_test.exs]: Done

File: apps/omg_watcher/lib/omg_watcher/exit_processor.ex (hunk 13 above)
Comment (pgebal) [reply apps/omg_watcher/lib/omg_watcher/exit_processor.ex]: Done

File: apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs (hunk 11 above)
Comment (pgebal) [reply apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs]: This was done on purpose. Those db_updates returned were in fact current state of ifes after finalizations are applied to the core. Even if nothing changes, db_updates will be produced. There should be a check that those updates are the same as in the line above.

After giving it a second thought, it feels more nautral to expect (as you expected) that those updates are "real" updates and are only produced when ifes are in fact changing. I refactored that.

File: apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs (hunk 9 above)
Comment (pgebal) [reply apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs]: Done. I left calls that use multiple piggybacks in argument list and those that test Core.new_piggybacks/2

File: apps/omg_watcher/lib/omg_watcher/exit_processor.ex [hunk 16]
```diff
@@ -273,8 +273,16 @@ defmodule OMG.Watcher.ExitProcessor do
...
+
+    {:ok, exits} = Core.prepare_utxo_exits_for_in_flight_exit_finalizations(state, finalizations)
+
+    # NOTE: it's not straightforward to track from utxo position returned when exiting utxo in State to ife id
+    # See issue #671 https://github.com/omisego/elixir-omg/issues/671
+    {invalidities, state_db_updates} = Enum.reduce(exits, {%{}, []}, &collect_invalidities_and_state_db_updates/2)
+
+    {:ok, state, db_updates} = Core.finalize_in_flight_exits(state, finalizations, invalidities)
+
+    {:reply, {:ok, state_db_updates ++ db_updates}, state}
```
Comment (InoMurko) [inline apps/omg_watcher/lib/omg_watcher/exit_processor.ex]: maybe you can prepend these lists?
