### PR TITLE
Fix: handle error when childchain is unreachable

### LINKED ISSUE #1308: /fees.all: Protocol Jason.Encoder not implemented for {:error, %HTTPoison.Error{id: nil, reason: :econnrefused}
`/fees.all`

```
Protocol.UndefinedError: protocol Jason.Encoder not implemented for {:error, %HTTPoison.Error{id: nil, reason: :econnrefused}}, Jason.Encoder protocol must always be explicitly implemented. This protocol is implemented for: OMG.WatcherInfo.DB.Transaction, Ecto.Association.NotLoaded, Ecto.Schema.Metadata, Float, BitString, Decimal, Atom, Date, NaiveDateTime, Map, Time, Jason.Fragment, DateTime, List, Any, Integer
  File "lib/jason.ex", line 199, in Jason.encode_to_iodata!/2
  File "lib/phoenix/controller.ex", line 729, in Phoenix.Controller.__put_render__/5
  File "lib/web/endpoint.ex", line 15, in OMG.WatcherRPC.Web.Endpoint.instrument/4
  File "lib/phoenix/controller.ex", line 746, in Phoenix.Controller.instrument_render_and_send/4
  File "lib/web/controllers/fee.ex", line 15, in OMG.WatcherRPC.Web.Controller.Fee.action/2
  File "lib/web/controllers/fee.ex", line 15, in OMG.WatcherRPC.Web.Controller.Fee.phoenix_controller_pipeline/2
  File "lib/web/endpoint.ex", line 15, in OMG.WatcherRPC.Web.Endpoint.instrument/4
  File "lib/spandex_phoenix.ex", line 156, in OMG.WatcherRPC.Web.Controller.Fee.call/2
```

### PR DESCRIPTION
**Pull request by mederic-p**
Closes #1308 

## Overview

This PR adds the support for Poison connection error when the watcher queries the childchain in `fees.all`. 

## Testing

Run a watcher with a childchain that is unreachable and call `fees.all`

### CODE REVIEW

File: apps/omg_watcher_info/lib/omg_watcher_info/http_rpc/adapter.ex [hunk 1]
```diff
@@ -53,7 +53,11 @@ defmodule OMG.WatcherInfo.HttpRPC.Adapter do
   def get_unparsed_response_body(%HTTPoison.Response{body: error}),
     do: {:error, {:server_error, error}}
 
-  def get_unparsed_response_body(error), do: {:error, {:client_error, error}}
+  def get_unparsed_response_body({:error, %HTTPoison.Error{reason: reason}}) do
```
Comment (unnawut) [inline apps/omg_watcher_info/lib/omg_watcher_info/http_rpc/adapter.ex]: Can you add a test for this new code? 🙇

File: apps/omg_watcher_rpc/lib/web/controllers/fallback.ex [hunk 2]
```diff
@@ -42,8 +42,8 @@ defmodule OMG.WatcherRPC.Web.Controller.Fallback do
       description: "No transaction that created input."
     },
     econnrefused: %{
-      code: "get_status:econnrefused",
-      description: "Cannot connect to the Ethereum node."
+      code: "client:econnrefused",
+      description: "Cannot communicate with the server."
```
Comment (T-Dnzt) [inline apps/omg_watcher_rpc/lib/web/controllers/fallback.ex]: Could be a bit more explicit here and say `Childchain` maybe?
