### PR TITLE
use different port for subscription worker

### LINKED ISSUE #1069: OMG.Eth.SubscriptionWorkerTest flaky
Passed here: https://circleci.com/gh/omisego/elixir-omg/22852 and here https://circleci.com/gh/omisego/elixir-omg/23232

Failed here: https://circleci.com/gh/omisego/elixir-omg/23114 and https://circleci.com/gh/omisego/elixir-omg/23228

The test just seems to freeze and timeout, normally it executes very fast

### PR DESCRIPTION
**Pull request by achiurizo**
📋 Closes #1069

## Overview

Changes the port to avoid collision with other [websocketex agent mock](https://github.com/omisego/elixir-omg/blob/master/apps/omg_eth/test/omg_eth/ethereum_client_monitor_test.exs#L28).

## Changes

Changes the port so they don't collide.

## Testing

```
mix test --include common
```

### CODE REVIEW

**Comment by chrishunt** [comment]
I think it's still timing out:

```
OMG.Eth.SubscriptionWorkerTest
  * test that worker can subscribe to different events and receive eventsToo long with no output (exceeded 10m0s)
```

**Comment by achiurizo** [comment]
@chrishunt gah, it was colliding on ports because it was in use. I need to dig in more why this is timing out now.

File: apps/omg_eth/test/omg_eth/subscription_worker_test.exs [hunk 1]
```diff
@@ -25,7 +25,7 @@ defmodule OMG.Eth.SubscriptionWorkerTest do
   @moduletag :common
 
   setup do
-    _ = Agent.start_link(fn -> 55_555 end, name: :port_holder)
+    _ = Agent.start_link(fn -> 55_556 end, name: :subscription_port_holder)
```
Comment (InoMurko) [inline apps/omg_eth/test/omg_eth/subscription_worker_test.exs]: It might be better if you go into a different range. Others take 55_555 as the starting port and gradually increment :)

Comment (InoMurko) [inline apps/omg_eth/test/omg_eth/subscription_worker_test.exs]:
```suggestion
    _ = Agent.start_link(fn -> 55_600 end, name: :subscription_port_holder)
```

File: apps/omg_eth/test/omg_eth/subscription_worker_test.exs [hunk 2]
```diff
@@ -25,7 +25,7 @@ defmodule OMG.Eth.SubscriptionWorkerTest do
   @moduletag :common
 
   setup do
-    _ = Agent.start_link(fn -> 55_555 end, name: :port_holder)
+    _ = Agent.start_link(fn -> 66_666 end, name: :subscription_port_holder)
```
Comment (InoMurko) [inline apps/omg_eth/test/omg_eth/subscription_worker_test.exs]:
```suggestion
    _ = Agent.start_link(fn -> 55_600 end, name: :subscription_port_holder)
```
